# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 802)
        MainWindow.setStyleSheet("background-color: #1b1d23")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.DesignPage = QtWidgets.QWidget()
        self.DesignPage.setObjectName("DesignPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DesignPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.DesignPage)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.zPlaneCircle = PlotWidget(self.DesignPage)
        self.zPlaneCircle.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.zPlaneCircle.setObjectName("zPlaneCircle")
        self.verticalLayout_10.addWidget(self.zPlaneCircle)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.checkBox_4 = QtWidgets.QCheckBox(self.DesignPage)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_18.addWidget(self.checkBox_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.radioButton_2 = QtWidgets.QRadioButton(self.DesignPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:white;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_19.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.DesignPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:white;")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_19.addWidget(self.radioButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.comboBox_4 = QtWidgets.QComboBox(self.DesignPage)
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    font-family: \"Overpass\";\n"
"    font-weight: 600; /* Semibold */\n"
"    font-size: 10pt; /* Adjust the font size as needed */\n"
"    color: white; /* Set the text color to white */\n"
"    border: 1px solid white; /* Set the border to 1px solid white */\n"
"background: rgba(74, 74, 74, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_4)
        self.clear_4 = QtWidgets.QPushButton(self.DesignPage)
        font = QtGui.QFont()
        font.setFamily("-apple-system")
        font.setPointSize(11)
        self.clear_4.setFont(font)
        self.clear_4.setStyleSheet("QPushButton{\n"
"  appearance: button;\n"
"  border-radius: 6px;\n"
"  border-width: 0;\n"
"  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(22, 25, 76);\n"
"  cursor: pointer;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"  height: 30px;\n"
"  margin: 0 20px 0 20px;\n"
"  position: center;\n"
"  width:70px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #283999;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #1c2973;\n"
"}")
        self.clear_4.setObjectName("clear_4")
        self.horizontalLayout_20.addWidget(self.clear_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(20, -1, 20, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_20 = QtWidgets.QLabel(self.DesignPage)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_11.addWidget(self.label_20)
        self.magPlot = PlotWidget(self.DesignPage)
        self.magPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.magPlot.setObjectName("magPlot")
        self.verticalLayout_11.addWidget(self.magPlot)
        self.label_21 = QtWidgets.QLabel(self.DesignPage)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.phasePlot = PlotWidget(self.DesignPage)
        self.phasePlot.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.phasePlot.setObjectName("phasePlot")
        self.verticalLayout_11.addWidget(self.phasePlot)
        self.correctPhase_4 = QtWidgets.QPushButton(self.DesignPage)
        font = QtGui.QFont()
        font.setFamily("-apple-system")
        font.setPointSize(11)
        self.correctPhase_4.setFont(font)
        self.correctPhase_4.setStyleSheet("QPushButton{\n"
"  appearance: button;\n"
"  border-radius: 6px;\n"
"  border-width: 0;\n"
"  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(22, 25, 76);\n"
"  cursor: pointer;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"  height: 30px;\n"
"  margin: 0 20px 0 20px;\n"
"  position: center;\n"
"  width:70px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #283999;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #1c2973;\n"
"}")
        self.correctPhase_4.setObjectName("correctPhase_4")
        self.verticalLayout_11.addWidget(self.correctPhase_4)
        self.verticalLayout_11.setStretch(1, 4)
        self.verticalLayout_11.setStretch(3, 4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.DesignPage)
        self.CorrectPage = QtWidgets.QWidget()
        self.CorrectPage.setObjectName("CorrectPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.CorrectPage)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.CorrectPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_12.addWidget(self.label_24)
        self.AllpassZplane = PlotWidget(self.CorrectPage)
        self.AllpassZplane.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.AllpassZplane.setObjectName("AllpassZplane")
        self.verticalLayout_12.addWidget(self.AllpassZplane)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        spacerItem4 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.CorrectPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.InsertFilterText = QtWidgets.QLineEdit(self.CorrectPage)
        self.InsertFilterText.setStyleSheet("color:white;\n"
"")
        self.InsertFilterText.setObjectName("InsertFilterText")
        self.verticalLayout_12.addWidget(self.InsertFilterText)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.comboBox = QtWidgets.QComboBox(self.CorrectPage)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_24.addWidget(self.comboBox)
        self.AddFilter = QtWidgets.QPushButton(self.CorrectPage)
        self.AddFilter.setStyleSheet("QPushButton{\n"
"  appearance: button;\n"
"  border-radius: 6px;\n"
"  border-width: 0;\n"
"  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(22, 25, 76);\n"
"  cursor: pointer;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"  height: 30px;\n"
"  margin: 0 20px 0 20px;\n"
"  position: center;\n"
"  width:70px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #283999;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #1c2973;\n"
"}")
        self.AddFilter.setObjectName("AddFilter")
        self.horizontalLayout_24.addWidget(self.AddFilter)
        self.Apply = QtWidgets.QPushButton(self.CorrectPage)
        self.Apply.setStyleSheet("QPushButton{\n"
"  appearance: button;\n"
"  border-radius: 6px;\n"
"  border-width: 0;\n"
"  box-shadow: rgba(50, 50, 93, .1) 0 0 0 1px inset,rgba(50, 50, 93, .1) 0 2px 5px 0,rgba(0, 0, 0, .07) 0 1px 1px 0;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(22, 25, 76);\n"
"  cursor: pointer;\n"
"  font-family: -apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Ubuntu,sans-serif;\n"
"  height: 30px;\n"
"  margin: 0 20px 0 20px;\n"
"  position: center;\n"
"  width:70px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #283999;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #1c2973;\n"
"}")
        self.Apply.setObjectName("Apply")
        self.horizontalLayout_24.addWidget(self.Apply)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        spacerItem5 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.verticalLayout_12.setStretch(1, 1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(20, -1, 20, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.CorrectPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_13.addWidget(self.label_25)
        self.AllPassMagPlot = PlotWidget(self.CorrectPage)
        self.AllPassMagPlot.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.AllPassMagPlot.setObjectName("AllPassMagPlot")
        self.verticalLayout_13.addWidget(self.AllPassMagPlot)
        self.label_26 = QtWidgets.QLabel(self.CorrectPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.AllPassPhasePlot = PlotWidget(self.CorrectPage)
        self.AllPassPhasePlot.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.AllPassPhasePlot.setObjectName("AllPassPhasePlot")
        self.verticalLayout_13.addWidget(self.AllPassPhasePlot)
        self.verticalLayout_13.setStretch(1, 4)
        self.verticalLayout_13.setStretch(3, 4)
        self.horizontalLayout_21.addLayout(self.verticalLayout_13)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 1)
        self.gridLayout_7.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.CorrectPage)
        self.ApplyPage = QtWidgets.QWidget()
        self.ApplyPage.setObjectName("ApplyPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ApplyPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.ApplyPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:white;")
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.InputSignal = PlotWidget(self.frame_2)
        self.InputSignal.setMinimumSize(QtCore.QSize(0, 200))
        self.InputSignal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.InputSignal.setObjectName("InputSignal")
        self.gridLayout_4.addWidget(self.InputSignal, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:white;")
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 2, 0, 1, 1)
        self.OutputFilteredSignal = PlotWidget(self.frame_2)
        self.OutputFilteredSignal.setMinimumSize(QtCore.QSize(0, 200))
        self.OutputFilteredSignal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.OutputFilteredSignal.setObjectName("OutputFilteredSignal")
        self.gridLayout_4.addWidget(self.OutputFilteredSignal, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.Touchpadcheckbox = QtWidgets.QRadioButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Touchpadcheckbox.setFont(font)
        self.Touchpadcheckbox.setStyleSheet("color:white;\n"
"font-weight:10000px;")
        self.Touchpadcheckbox.setObjectName("Touchpadcheckbox")
        self.gridLayout_3.addWidget(self.Touchpadcheckbox, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.Touchpad = QtWidgets.QGraphicsView(self.frame_3)
        self.Touchpad.setMaximumSize(QtCore.QSize(16777215, 300))
        self.Touchpad.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Touchpad.setObjectName("Touchpad")
        self.gridLayout_3.addWidget(self.Touchpad, 2, 0, 1, 2)
        self.label_2.raise_()
        self.horizontalSlider.raise_()
        self.Touchpad.raise_()
        self.Touchpadcheckbox.raise_()
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.ApplyPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 26))
        self.menubar.setStyleSheet("color:white;")
        self.menubar.setObjectName("menubar")
        self.menuDesign = QtWidgets.QMenu(self.menubar)
        self.menuDesign.setStyleSheet("color:white;\n"
"")
        self.menuDesign.setObjectName("menuDesign")
        self.menuImplement = QtWidgets.QMenu(self.menubar)
        self.menuImplement.setStyleSheet("color:white;")
        self.menuImplement.setObjectName("menuImplement")
        self.menuApply = QtWidgets.QMenu(self.menubar)
        self.menuApply.setObjectName("menuApply")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionDesign = QtWidgets.QAction(MainWindow)
        self.actionDesign.setObjectName("actionDesign")
        self.actionAdjust_Phase = QtWidgets.QAction(MainWindow)
        self.actionAdjust_Phase.setObjectName("actionAdjust_Phase")
        self.actionApply = QtWidgets.QAction(MainWindow)
        self.actionApply.setObjectName("actionApply")
        self.menuDesign.addAction(self.actionOpen)
        self.menuImplement.addAction(self.actionAdjust_Phase)
        self.menuImplement.addAction(self.actionDesign)
        self.menuImplement.addAction(self.actionApply)
        self.menubar.addAction(self.menuDesign.menuAction())
        self.menubar.addAction(self.menuImplement.menuAction())
        self.menubar.addAction(self.menuApply.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "Z_Plane Circle "))
        self.checkBox_4.setText(_translate("MainWindow", "conjugates"))
        self.radioButton_2.setText(_translate("MainWindow", "Zeros"))
        self.radioButton.setText(_translate("MainWindow", "Poles"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "zeros"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "poles"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "both"))
        self.clear_4.setText(_translate("MainWindow", "Clear"))
        self.label_20.setText(_translate("MainWindow", "Magnitude Response"))
        self.label_21.setText(_translate("MainWindow", "Phase Response"))
        self.correctPhase_4.setText(_translate("MainWindow", "Correct Phase"))
        self.label_24.setText(_translate("MainWindow", "Z_Plane Circle "))
        self.label.setText(_translate("MainWindow", "All Pass Filters"))
        self.AddFilter.setText(_translate("MainWindow", "Add"))
        self.Apply.setText(_translate("MainWindow", "Apply"))
        self.label_25.setText(_translate("MainWindow", "Magnitude Response"))
        self.label_26.setText(_translate("MainWindow", "Phase Response"))
        self.label_23.setText(_translate("MainWindow", "Input"))
        self.label_22.setText(_translate("MainWindow", "Output"))
        self.Touchpadcheckbox.setText(_translate("MainWindow", "Touch Pad"))
        self.label_2.setText(_translate("MainWindow", "FIlterSpeed"))
        self.menuDesign.setTitle(_translate("MainWindow", "File"))
        self.menuImplement.setTitle(_translate("MainWindow", "Tab"))
        self.menuApply.setTitle(_translate("MainWindow", "Apply"))
        self.actionOpen.setText(_translate("MainWindow", "Load"))
        self.actionDesign.setText(_translate("MainWindow", "Design"))
        self.actionAdjust_Phase.setText(_translate("MainWindow", "Correct Phase"))
        self.actionApply.setText(_translate("MainWindow", "Apply"))
from pyqtgraph import PlotWidget
